export default [
    { code: 4, label: "Afghanistan", alpha2: "af", alpha3: "afg"},
    { code: 710, label: "Afrique du Sud", alpha2: "za", alpha3: "zaf"},
    { code: 248, label: "Îles Åland", alpha2: "ax", alpha3: "ala"},
    { code: 8, label: "Albanie", alpha2: "al", alpha3: "alb"},
    { code: 12, label: "Algérie", alpha2: "dz", alpha3: "dza"},
    { code: 276, label: "Allemagne", alpha2: "de", alpha3: "deu"},
    { code: 20, label: "Andorre", alpha2: "ad", alpha3: "and"},
    { code: 24, label: "Angola", alpha2: "ao", alpha3: "ago"},
    { code: 660, label: "Anguilla", alpha2: "ai", alpha3: "aia"},
    { code: 10, label: "Antarctique", alpha2: "aq", alpha3: "ata"},
    { code: 28, label: "Antigua-et-Barbuda", alpha2: "ag", alpha3: "atg"},
    { code: 682, label: "Arabie saoudite", alpha2: "sa", alpha3: "sau"},
    { code: 32, label: "Argentine", alpha2: "ar", alpha3: "arg"},
    { code: 51, label: "Arménie", alpha2: "am", alpha3: "arm"},
    { code: 533, label: "Aruba", alpha2: "aw", alpha3: "abw"},
    { code: 36, label: "Australie", alpha2: "au", alpha3: "aus"},
    { code: 40, label: "Autriche", alpha2: "at", alpha3: "aut"},
    { code: 31, label: "Azerbaïdjan", alpha2: "az", alpha3: "aze"},
    { code: 44, label: "Bahamas", alpha2: "bs", alpha3: "bhs"},
    { code: 48, label: "Bahreïn", alpha2: "bh", alpha3: "bhr"},
    { code: 50, label: "Bangladesh", alpha2: "bd", alpha3: "bgd"},
    { code: 52, label: "Barbade", alpha2: "bb", alpha3: "brb"},
    { code: 112, label: "Biélorussie", alpha2: "by", alpha3: "blr"},
    { code: 56, label: "Belgique", alpha2: "be", alpha3: "bel"},
    { code: 84, label: "Belize", alpha2: "bz", alpha3: "blz"},
    { code: 204, label: "Bénin", alpha2: "bj", alpha3: "ben"},
    { code: 60, label: "Bermudes", alpha2: "bm", alpha3: "bmu"},
    { code: 64, label: "Bhoutan", alpha2: "bt", alpha3: "btn"},
    { code: 68, label: "Bolivie", alpha2: "bo", alpha3: "bol"},
    { code: 535, label: "Pays-Bas caribéens", alpha2: "bq", alpha3: "bes"},
    { code: 70, label: "Bosnie-Herzégovine", alpha2: "ba", alpha3: "bih"},
    { code: 72, label: "Botswana", alpha2: "bw", alpha3: "bwa"},
    { code: 74, label: "Île Bouvet", alpha2: "bv", alpha3: "bvt"},
    { code: 76, label: "Brésil", alpha2: "br", alpha3: "bra"},
    { code: 96, label: "Brunei", alpha2: "bn", alpha3: "brn"},
    { code: 100, label: "Bulgarie", alpha2: "bg", alpha3: "bgr"},
    { code: 854, label: "Burkina Faso", alpha2: "bf", alpha3: "bfa"},
    { code: 108, label: "Burundi", alpha2: "bi", alpha3: "bdi"},
    { code: 136, label: "Îles Caïmans", alpha2: "ky", alpha3: "cym"},
    { code: 116, label: "Cambodge", alpha2: "kh", alpha3: "khm"},
    { code: 120, label: "Cameroun", alpha2: "cm", alpha3: "cmr"},
    { code: 124, label: "Canada", alpha2: "ca", alpha3: "can"},
    { code: 132, label: "Cap-Vert", alpha2: "cv", alpha3: "cpv"},
    { code: 140, label: "République centrafricaine", alpha2: "cf", alpha3: "caf"},
    { code: 152, label: "Chili", alpha2: "cl", alpha3: "chl"},
    { code: 156, label: "Chine", alpha2: "cn", alpha3: "chn"},
    { code: 162, label: "Île Christmas", alpha2: "cx", alpha3: "cxr"},
    { code: 196, label: "Chypre (pays)", alpha2: "cy", alpha3: "cyp"},
    { code: 166, label: "Îles Cocos", alpha2: "cc", alpha3: "cck"},
    { code: 170, label: "Colombie", alpha2: "co", alpha3: "col"},
    { code: 174, label: "Comores (pays)", alpha2: "km", alpha3: "com"},
    { code: 178, label: "République du Congo", alpha2: "cg", alpha3: "cog"},
    { code: 180, label: "République démocratique du Congo", alpha2: "cd", alpha3: "cod"},
    { code: 184, label: "Îles Cook", alpha2: "ck", alpha3: "cok"},
    { code: 410, label: "Corée du Sud", alpha2: "kr", alpha3: "kor"},
    { code: 408, label: "Corée du Nord", alpha2: "kp", alpha3: "prk"},
    { code: 188, label: "Costa Rica", alpha2: "cr", alpha3: "cri"},
    { code: 384, label: "Côte d'Ivoire", alpha2: "ci", alpha3: "civ"},
    { code: 191, label: "Croatie", alpha2: "hr", alpha3: "hrv"},
    { code: 192, label: "Cuba", alpha2: "cu", alpha3: "cub"},
    { code: 531, label: "Curaçao", alpha2: "cw", alpha3: "cuw"},
    { code: 208, label: "Danemark", alpha2: "dk", alpha3: "dnk"},
    { code: 262, label: "Djibouti", alpha2: "dj", alpha3: "dji"},
    { code: 214, label: "République dominicaine", alpha2: "do", alpha3: "dom"},
    { code: 212, label: "Dominique", alpha2: "dm", alpha3: "dma"},
    { code: 818, label: "Égypte", alpha2: "eg", alpha3: "egy"},
    { code: 222, label: "Salvador", alpha2: "sv", alpha3: "slv"},
    { code: 784, label: "Émirats arabes unis", alpha2: "ae", alpha3: "are"},
    { code: 218, label: "Équateur (pays)", alpha2: "ec", alpha3: "ecu"},
    { code: 232, label: "Érythrée", alpha2: "er", alpha3: "eri"},
    { code: 724, label: "Espagne", alpha2: "es", alpha3: "esp"},
    { code: 233, label: "Estonie", alpha2: "ee", alpha3: "est"},
    { code: 840, label: "États-Unis", alpha2: "us", alpha3: "usa"},
    { code: 231, label: "Éthiopie", alpha2: "et", alpha3: "eth"},
    { code: 238, label: "Malouines", alpha2: "fk", alpha3: "flk"},
    { code: 234, label: "Îles Féroé", alpha2: "fo", alpha3: "fro"},
    { code: 242, label: "Fidji", alpha2: "fj", alpha3: "fji"},
    { code: 246, label: "Finlande", alpha2: "fi", alpha3: "fin"},
    { code: 250, label: "France", alpha2: "fr", alpha3: "fra"},
    { code: 266, label: "Gabon", alpha2: "ga", alpha3: "gab"},
    { code: 270, label: "Gambie", alpha2: "gm", alpha3: "gmb"},
    { code: 268, label: "Géorgie (pays)", alpha2: "ge", alpha3: "geo"},
    { code: 239, label: "Géorgie du Sud-et-les îles Sandwich du Sud", alpha2: "gs", alpha3: "sgs"},
    { code: 288, label: "Ghana", alpha2: "gh", alpha3: "gha"},
    { code: 292, label: "Gibraltar", alpha2: "gi", alpha3: "gib"},
    { code: 300, label: "Grèce", alpha2: "gr", alpha3: "grc"},
    { code: 308, label: "Grenade (pays)", alpha2: "gd", alpha3: "grd"},
    { code: 304, label: "Groenland", alpha2: "gl", alpha3: "grl"},
    { code: 312, label: "Guadeloupe", alpha2: "gp", alpha3: "glp"},
    { code: 316, label: "Guam", alpha2: "gu", alpha3: "gum"},
    { code: 320, label: "Guatemala", alpha2: "gt", alpha3: "gtm"},
    { code: 831, label: "Guernesey", alpha2: "gg", alpha3: "ggy"},
    { code: 324, label: "Guinée", alpha2: "gn", alpha3: "gin"},
    { code: 624, label: "Guinée-Bissau", alpha2: "gw", alpha3: "gnb"},
    { code: 226, label: "Guinée équatoriale", alpha2: "gq", alpha3: "gnq"},
    { code: 328, label: "Guyana", alpha2: "gy", alpha3: "guy"},
    { code: 254, label: "Guyane", alpha2: "gf", alpha3: "guf"},
    { code: 332, label: "Haïti", alpha2: "ht", alpha3: "hti"},
    { code: 334, label: "Îles Heard-et-MacDonald", alpha2: "hm", alpha3: "hmd"},
    { code: 340, label: "Honduras", alpha2: "hn", alpha3: "hnd"},
    { code: 344, label: "Hong Kong", alpha2: "hk", alpha3: "hkg"},
    { code: 348, label: "Hongrie", alpha2: "hu", alpha3: "hun"},
    { code: 833, label: "Île de Man", alpha2: "im", alpha3: "imn"},
    { code: 581, label: "Îles mineures éloignées des États-Unis", alpha2: "um", alpha3: "umi"},
    { code: 92, label: "Îles Vierges britanniques", alpha2: "vg", alpha3: "vgb"},
    { code: 850, label: "Îles Vierges des États-Unis", alpha2: "vi", alpha3: "vir"},
    { code: 356, label: "Inde", alpha2: "in", alpha3: "ind"},
    { code: 360, label: "Indonésie", alpha2:  "id",  alpha3:  "idn"},
    { code: 364, label: "Iran", alpha2: "ir", alpha3: "irn"},
    { code: 368, label: "Irak", alpha2: "iq", alpha3: "irq"},
    { code: 372, label: "Irlande (pays)", alpha2: "ie", alpha3: "irl"},
    { code: 352, label: "Islande", alpha2: "is", alpha3: "isl"},
    { code: 376, label: "Israël", alpha2: "il", alpha3: "isr"},
    { code: 380, label: "Italie", alpha2: "it", alpha3: "ita"},
    { code: 388, label: "Jamaïque", alpha2: "jm", alpha3: "jam"},
    { code: 392, label: "Japon", alpha2: "jp", alpha3: "jpn"},
    { code: 832, label: "Jersey", alpha2: "je", alpha3: "jey"},
    { code: 400, label: "Jordanie", alpha2: "jo", alpha3: "jor"},
    { code: 398, label: "Kazakhstan", alpha2: "kz", alpha3: "kaz"},
    { code: 404, label: "Kenya", alpha2: "ke", alpha3: "ken"},
    { code: 417, label: "Kirghizistan", alpha2: "kg", alpha3: "kgz"},
    { code: 296, label: "Kiribati", alpha2: "ki", alpha3: "kir"},
    { code: 414, label: "Koweït", alpha2: "kw", alpha3: "kwt"},
    { code: 418, label: "Laos", alpha2: "la", alpha3: "lao"},
    { code: 426, label: "Lesotho", alpha2: "ls", alpha3: "lso"},
    { code: 428, label: "Lettonie", alpha2: "lv", alpha3: "lva"},
    { code: 422, label: "Liban", alpha2: "lb", alpha3: "lbn"},
    { code: 430, label: "Liberia", alpha2: "lr", alpha3: "lbr"},
    { code: 434, label: "Libye", alpha2: "ly", alpha3: "lby"},
    { code: 438, label: "Liechtenstein", alpha2: "li", alpha3: "lie"},
    { code: 440, label: "Lituanie", alpha2: "lt", alpha3: "ltu"},
    { code: 442, label: "Luxembourg (pays)", alpha2: "lu", alpha3: "lux"},
    { code: 446, label: "Macao", alpha2: "mo", alpha3: "mac"},
    { code: 807, label: "Macédoine du Nord", alpha2: "mk", alpha3: "mkd"},
    { code: 450, label: "Madagascar", alpha2: "mg", alpha3: "mdg"},
    { code: 458, label: "Malaisie", alpha2: "my", alpha3: "mys"},
    { code: 454, label: "Malawi", alpha2: "mw", alpha3: "mwi"},
    { code: 462, label: "Maldives", alpha2: "mv", alpha3: "mdv"},
    { code: 466, label: "Mali", alpha2: "ml", alpha3: "mli"},
    { code: 470, label: "Malte", alpha2: "mt", alpha3: "mlt"},
    { code: 580, label: "Îles Mariannes du Nord", alpha2: "mp", alpha3: "mnp"},
    { code: 504, label: "Maroc", alpha2: "ma", alpha3: "mar"},
    { code: 584, label: "Îles Marshall (pays)", alpha2: "mh", alpha3: "mhl"},
    { code: 474, label: "Martinique", alpha2: "mq", alpha3: "mtq"},
    { code: 480, label: "Maurice (pays)", alpha2: "mu", alpha3: "mus"},
    { code: 478, label: "Mauritanie", alpha2: "mr", alpha3: "mrt"},
    { code: 175, label: "Mayotte", alpha2: "yt", alpha3: "myt"},
    { code: 484, label: "Mexique", alpha2: "mx", alpha3: "mex"},
    { code: 583, label: "États fédérés de Micronésie (pays)", alpha2: "fm", alpha3: "fsm"},
    { code: 498, label: "Moldavie", alpha2: "md", alpha3: "mda"},
    { code: 492, label: "Monaco", alpha2: "mc", alpha3: "mco"},
    { code: 496, label: "Mongolie", alpha2: "mn", alpha3: "mng"},
    { code: 499, label: "Monténégro", alpha2: "me", alpha3: "mne"},
    { code: 500, label: "Montserrat", alpha2: "ms", alpha3: "msr"},
    { code: 508, label: "Mozambique", alpha2: "mz", alpha3: "moz"},
    { code: 104, label: "Birmanie", alpha2: "mm", alpha3: "mmr"},
    { code: 516, label: "Namibie", alpha2: "na", alpha3: "nam"},
    { code: 520, label: "Nauru", alpha2: "nr", alpha3: "nru"},
    { code: 524, label: "Népal", alpha2: "np", alpha3: "npl"},
    { code: 558, label: "Nicaragua", alpha2: "ni", alpha3: "nic"},
    { code: 562, label: "Niger", alpha2: "ne", alpha3: "ner"},
    { code: 566, label: "Nigeria", alpha2: "ng", alpha3: "nga"},
    { code: 570, label: "Niue", alpha2: "nu", alpha3: "niu"},
    { code: 574, label: "Île Norfolk", alpha2: "nf", alpha3: "nfk"},
    { code: 578, label: "Norvège", alpha2: "no", alpha3: "nor"},
    { code: 540, label: "Nouvelle-Calédonie", alpha2: "nc", alpha3: "ncl"},
    { code: 554, label: "Nouvelle-Zélande", alpha2: "nz", alpha3: "nzl"},
    { code: 86, label: "Territoire britannique de l'océan Indien", alpha2: "io", alpha3: "iot"},
    { code: 512, label: "Oman", alpha2: "om", alpha3: "omn"},
    { code: 800, label: "Ouganda", alpha2: "ug", alpha3: "uga"},
    { code: 860, label: "Ouzbékistan", alpha2: "uz", alpha3: "uzb"},
    { code: 586, label: "Pakistan", alpha2: "pk", alpha3: "pak"},
    { code: 585, label: "Palaos", alpha2: "pw", alpha3: "plw"},
    { code: 275, label: "Palestine", alpha2: "ps", alpha3: "pse"},
    { code: 591, label: "Panama", alpha2: "pa", alpha3: "pan"},
    { code: 598, label: "Papouasie-Nouvelle-Guinée", alpha2: "pg", alpha3: "png"},
    { code: 600, label: "Paraguay", alpha2: "py", alpha3: "pry"},
    { code: 528, label: "Pays-Bas", alpha2: "nl", alpha3: "nld"},
    { code: 604, label: "Pérou", alpha2: "pe", alpha3: "per"},
    { code: 608, label: "Philippines", alpha2: "ph", alpha3: "phl"},
    { code: 612, label: "Îles Pitcairn", alpha2: "pn", alpha3: "pcn"},
    { code: 616, label: "Pologne", alpha2: "pl", alpha3: "pol"},
    { code: 258, label: "Polynésie française", alpha2: "pf", alpha3: "pyf"},
    { code: 630, label: "Porto Rico", alpha2: "pr", alpha3: "pri"},
    { code: 620, label: "Portugal", alpha2: "pt", alpha3: "prt"},
    { code: 634, label: "Qatar", alpha2: "qa", alpha3: "qat"},
    { code: 638, label: "La Réunion", alpha2: "re", alpha3: "reu"},
    { code: 642, label: "Roumanie", alpha2: "ro", alpha3: "rou"},
    { code: 826, label: "Royaume-Uni", alpha2: "gb", alpha3: "gbr"},
    { code: 643, label: "Russie", alpha2: "ru", alpha3: "rus"},
    { code: 646, label: "Rwanda", alpha2: "rw", alpha3: "rwa"},
    { code: 732, label: "République arabe sahraouie démocratique", alpha2: "eh", alpha3: "esh"},
    { code: 652, label: "Saint-Barthélemy", alpha2: "bl", alpha3: "blm"},
    { code: 659, label: "Saint-Christophe-et-Niévès", alpha2: "kn", alpha3: "kna"},
    { code: 674, label: "Saint-Marin", alpha2: "sm", alpha3: "smr"},
    { code: 663, label: "Saint-Martin", alpha2: "mf", alpha3: "maf"},
    { code: 534, label: "Saint-Martin", alpha2: "sx", alpha3: "sxm"},
    { code: 666, label: "Saint-Pierre-et-Miquelon", alpha2: "pm", alpha3: "spm"},
    { code: 336, label: "Saint-Siège (État de la Cité du Vatican)", alpha2: "va", alpha3: "vat"},
    { code: 670, label: "Saint-Vincent-et-les-Grenadines", alpha2: "vc", alpha3: "vct"},
    { code: 654, label: "Sainte-Hélène, Ascension et Tristan da Cunha", alpha2: "sh", alpha3: "shn"},
    { code: 662, label: "Sainte-Lucie", alpha2: "lc", alpha3: "lca"},
    { code: 90, label: "Salomon", alpha2: "sb", alpha3: "slb"},
    { code: 882, label: "Samoa", alpha2: "ws", alpha3: "wsm"},
    { code: 16, label: "Samoa américaines", alpha2: "as", alpha3: "asm"},
    { code: 678, label: "Sao Tomé-et-Principe", alpha2: "st", alpha3: "stp"},
    { code: 686, label: "Sénégal", alpha2: "sn", alpha3: "sen"},
    { code: 688, label: "Serbie", alpha2: "rs", alpha3: "srb"},
    { code: 690, label: "Seychelles", alpha2: "sc", alpha3: "syc"},
    { code: 694, label: "Sierra Leone", alpha2: "sl", alpha3: "sle"},
    { code: 702, label: "Singapour", alpha2: "sg", alpha3: "sgp"},
    { code: 703, label: "Slovaquie", alpha2: "sk", alpha3: "svk"},
    { code: 705, label: "Slovénie", alpha2: "si", alpha3: "svn"},
    { code: 706, label: "Somalie", alpha2: "so", alpha3: "som"},
    { code: 729, label: "Soudan", alpha2: "sd", alpha3: "sdn"},
    { code: 728, label: "Soudan du Sud", alpha2: "ss", alpha3: "ssd"},
    { code: 144, label: "Sri Lanka", alpha2: "lk", alpha3: "lka"},
    { code: 752, label: "Suède", alpha2: "se", alpha3: "swe"},
    { code: 756, label: "Suisse", alpha2: "ch", alpha3: "che"},
    { code: 740, label: "Suriname", alpha2: "sr", alpha3: "sur"},
    { code: 744, label: "Svalbard et ile Jan Mayen", alpha2: "sj", alpha3: "sjm"},
    { code: 748, label: "Eswatini", alpha2: "sz", alpha3: "swz"},
    { code: 760, label: "Syrie", alpha2: "sy", alpha3: "syr"},
    { code: 762, label: "Tadjikistan", alpha2: "tj", alpha3: "tjk"},
    { code: 158, label: "Taïwan  (République de Chine (Taïwan))", alpha2: "tw", alpha3: "twn"},
    { code: 834, label: "Tanzanie", alpha2: "tz", alpha3: "tza"},
    { code: 148, label: "Tchad", alpha2: "td", alpha3: "tcd"},
    { code: 203, label: "Tchéquie", alpha2: "cz", alpha3: "cze"},
    { code: 260, label: "Terres australes et antarctiques françaises", alpha2: "tf", alpha3: "atf"},
    { code: 764, label: "Thaïlande", alpha2: "th", alpha3: "tha"},
    { code: 626, label: "Timor oriental", alpha2: "tl", alpha3: "tls"},
    { code: 768, label: "Togo", alpha2: "tg", alpha3: "tgo"},
    { code: 772, label: "Tokelau", alpha2: "tk", alpha3: "tkl"},
    { code: 776, label: "Tonga", alpha2: "to", alpha3: "ton"},
    { code: 780, label: "Trinité-et-Tobago", alpha2: "tt", alpha3: "tto"},
    { code: 788, label: "Tunisie", alpha2: "tn", alpha3: "tun"},
    { code: 795, label: "Turkménistan", alpha2: "tm", alpha3: "tkm"},
    { code: 796, label: "Îles Turques-et-Caïques", alpha2: "tc", alpha3: "tca"},
    { code: 792, label: "Turquie", alpha2: "tr", alpha3: "tur"},
    { code: 798, label: "Tuvalu", alpha2: "tv", alpha3: "tuv"},
    { code: 804, label: "Ukraine", alpha2: "ua", alpha3: "ukr"},
    { code: 858, label: "Uruguay", alpha2: "uy", alpha3: "ury"},
    { code: 548, label: "Vanuatu", alpha2: "vu", alpha3: "vut"},
    { code: 862, label: "Venezuela", alpha2: "ve", alpha3: "ven"},
    { code: 704, label: "Viêt Nam", alpha2: "vn", alpha3: "vnm"},
    { code: 876, label: "Wallis-et-Futuna", alpha2: "wf", alpha3: "wlf"},
    { code: 887, label: "Yémen", alpha2: "ye", alpha3: "yem"},
    { code: 894, label: "Zambie", alpha2: "zm", alpha3: "zmb"},
    { code: 716, label: "Zimbabwe", alpha2: "zw", alpha3: "zwe"},
];
